[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=0"
    Cache-Control = "no-store"

[[redirects]]
  from = "/certificate"
  to = "/certificate-404.html"
  status = 404